name: my-crud-infra-stack

# 1. Build & run
# docker compose -f docker-compose-infra.yml up -d

services:
  postgres:
    container_name: postgres
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - my-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  my-network:
    name: my-network