FROM jenkins/jenkins:latest-jdk21

USER root

RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    git \
    docker.io \
    maven \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/lib/docker/cli-plugins && \
    curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 \
    -o /usr/lib/docker/cli-plugins/docker-compose && \
    chmod +x /usr/lib/docker/cli-plugins/docker-compose

USER jenkins