services:
  my-crud-app-1:
    container_name: my-crud-app-1
    build:
      context: .
      dockerfile: Dockerfile
    image: my-crud-app:latest
    restart: unless-stopped
    ports:
      - "8091:8080"
    environment:
      INSTANCE_PORT: 8091
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/my_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123qwe
    networks:
      - mycrud_my-network

  my-crud-app-2:
    container_name: my-crud-app-2
    build:
      context: .
      dockerfile: Dockerfile
    image: my-crud-app:latest
    restart: unless-stopped
    ports:
      - "8092:8080"
    environment:
      INSTANCE_PORT: 8092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/my_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123qwe
    networks:
      - mycrud_my-network

networks:
  mycrud_my-network:
    external: true