name: my-crud-stack

# 1. Build & run
# docker compose up -d --build
# or with environment
# BUILD_NUMBER=latest docker compose up -d --build

services:
  my-crud:
    container_name: my-crud
    image: my-crud:${BUILD_NUMBER:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8100:8080"
    environment:
      INSTANCE_PORT: 8100
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/my_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123qwe
    networks:
      - my-network

networks:
  my-network:
    name: my-network