services:
  # 1. Postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge