name: my-crud-infra-stack

# 1. Build & run
# docker compose -f docker-compose-infra.yml up -d
# 2. Pull model
# docker exec -it ollama ollama pull llama3.2:1b

services:
  postgres:
    container_name: postgres
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - my-network
    gpus: all

volumes:
  postgres_data:
  ollama_data:

networks:
  my-network:
    name: my-network