spring:
  application:
    name: simple-crud
  profiles:
    active: ${PROFILE:dev}
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    build:
      enabled: true