spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/my_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123qwe}
  jpa:
    properties:
      hibernate:
        show_sql: true
  flyway:
    enabled: true
    clean-disabled: false

logging:
  level:
    com.errolito.mycrud: DEBUG

security:
  jwt:
    secret: 3IISQQSIJVQT80CWBCFLK1GAMTXMQ7MYQ8NSMUZT8OELD4ZEVCL820HWSFKLJMKT

springdoc:
  swagger-ui:
    persist-authorization: true