spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/my_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123qwe}
  jpa:
    properties:
      hibernate:
        show_sql: true
  flyway:
    enabled: true
    clean-disabled: false

  mongodb:
    uri: ${SPRING_MONGODB_URI:mongodb://root:123qwe@localhost:27017/my_db?authSource=admin}

logging:
  level:
    com.errolito.mycrud: DEBUG