spring:
  application:
    name: simple-crud
  profiles:
    active: ${PROFILE:dev}
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            temperature: 1
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    cache: false
  web:
    resources:
      add-mappings: true

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    build:
      enabled: true