input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  mutate {
    rename => { "level" => "log_level" }
  }

  if [stack_trace] {
    mutate {
      add_tag => ["has_exception"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "my-crud-app-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}