drop table if exists user_profiles cascade;
drop table if exists users cascade;
create table user_profiles
(
    id           integer generated by default as identity,
    created_date timestamp(6) with time zone default NOW() not null,
    full_name    varchar(255)                              not null,
    primary key (id)
);
create table users
(
    id              integer generated by default as identity,
    user_profile_id integer unique,
    created_date    timestamp(6) with time zone default NOW() not null,
    username        varchar(255)                              not null unique,
    primary key (id)
);
alter table if exists users add constraint fk_user_profile_id foreign key (user_profile_id) references user_profiles;
drop table if exists files cascade;
create table files
(
    id           integer generated by default as identity,
    created_date timestamp(6) with time zone default now() not null,
    name     varchar(255)                              not null,
    slug         varchar(255)                              not null,
    url          varchar(255)                              not null,
    primary key (id)
);

drop table if exists spring_ai_chat_memory cascade;
create table spring_ai_chat_memory
(
    id              integer generated by default as identity,
    conversation_id varchar(255)                              not null,
    content         text                                      not null,
    type            varchar(255)                              not null,
    timestamp       timestamp                                 not null
);