drop table if exists user_profiles cascade;
drop table if exists users cascade;
create table user_profiles
(
    id           integer generated by default as identity,
    created_date timestamp(6) with time zone default NOW() not null,
    full_name    varchar(255)                              not null,
    primary key (id)
);
create table users
(
    id              integer generated by default as identity,
    user_profile_id integer unique,
    created_date    timestamp(6) with time zone default NOW() not null,
    username        varchar(255)                              not null unique,
    primary key (id)
);
alter table if exists users add constraint fk_user_profile_id foreign key (user_profile_id) references user_profiles;

drop table if exists chat_messages cascade;
create table chat_messages
(
    id        bigint generated by default as identity,
    timestamp timestamp(6) with time zone default NOW() not null,
    content   TEXT                                      not null,
    room_id   varchar(255)                              not null,
    sender    varchar(255)                              not null,
    primary key (id)
);
create index idx_room_timestamp on chat_messages (room_id, timestamp);