alter table if exists role_permissions drop constraint if exists fk_role_permissions_permission_id;
alter table if exists role_permissions drop constraint if exists fk_role_permissions_role_id;
alter table if exists user_roles drop constraint if exists fk_user_roles_role_id;
alter table if exists user_roles drop constraint if exists fk_user_roles_user_id;
alter table if exists users drop constraint if exists fk_user_credential_id;
alter table if exists users drop constraint if exists fk_user_profile_id;
drop table if exists permissions cascade;
drop table if exists role_permissions cascade;
drop table if exists roles cascade;
drop table if exists user_credentials cascade;
drop table if exists user_profiles cascade;
drop table if exists user_roles cascade;
drop table if exists users cascade;
create table permissions
(
    id           integer generated by default as identity,
    created_date timestamp(6) with time zone default NOW() not null,
    name         varchar(255)                              not null,
    primary key (id)
);
create table role_permissions
(
    permission_id integer not null,
    role_id       integer not null,
    primary key (permission_id, role_id)
);
create table roles
(
    id           integer generated by default as identity,
    created_date timestamp(6) with time zone default NOW() not null,
    name         varchar(255)                              not null,
    primary key (id)
);
create table user_credentials
(
    id               integer generated by default as identity,
    created_date     timestamp(6) with time zone default NOW() not null,
    encoded_password varchar(255)                              not null,
    primary key (id)
);
create table user_profiles
(
    id           integer generated by default as identity,
    created_date timestamp(6) with time zone default NOW() not null,
    full_name    varchar(255)                              not null,
    primary key (id)
);
create table user_roles
(
    role_id integer not null,
    user_id integer not null,
    primary key (role_id, user_id)
);
create table users
(
    id                 integer generated by default as identity,
    user_credential_id integer unique,
    user_profile_id    integer unique,
    created_date       timestamp(6) with time zone default NOW() not null,
    username           varchar(255)                              not null unique,
    primary key (id)
);
alter table if exists role_permissions add constraint fk_role_permissions_permission_id foreign key (permission_id) references permissions;
alter table if exists role_permissions add constraint fk_role_permissions_role_id foreign key (role_id) references roles;
alter table if exists user_roles add constraint fk_user_roles_role_id foreign key (role_id) references roles;
alter table if exists user_roles add constraint fk_user_roles_user_id foreign key (user_id) references users;
alter table if exists users add constraint fk_user_credential_id foreign key (user_credential_id) references user_credentials;
alter table if exists users add constraint fk_user_profile_id foreign key (user_profile_id) references user_profiles;