insert into user_profiles (full_name)
values ('Darlena Runte'),
       ('Tamiko Feest'),
       ('Mel Rowe'),
       ('Dorie Stamm'),
       ('Derek Johns'),
       ('Cyrus Bartoletti'),
       ('Ezequiel Kub'),
       ('Anibal Greenholt'),
       ('Kaitlyn Gutmann'),
       ('Celinda Erdman'),
       ('Terina Nicolas'),
       ('Alene Zieme'),
       ('Cole Bins'),
       ('Christoper Legros'),
       ('Fausto Shanahan'),
       ('Stephen Barton'),
       ('Demetrius Borer'),
       ('Sanford Prohaska'),
       ('Noe Haley'),
       ('Henriette Turcotte'),
       ('Muriel Rath'),
       ('Racquel Bayer'),
       ('Tom Johns'),
       ('Damion Marvin'),
       ('Edmundo Powlowski'),
       ('Damon Hagenes'),
       ('Felton Greenfelder'),
       ('Erline Wuckert'),
       ('Georgann Gusikowski'),
       ('Susanne Watsica'),
       ('Leland Gusikowski'),
       ('Sharice Hills'),
       ('Shaina Jacobs'),
       ('Danilo Lubowitz'),
       ('Herman Kertzmann'),
       ('Marybelle Lowe'),
       ('Edwardo Rodriguez'),
       ('Gabriella Berge'),
       ('Sal Ziemann'),
       ('Everette Macejkovic'),
       ('Justine Mraz'),
       ('Joshua Reichel'),
       ('Serafina Mertz'),
       ('Erwin Turner'),
       ('Ena Gutkowski'),
       ('Nicola Hyatt'),
       ('Elton Cummerata'),
       ('Carin O''Hara'),
       ('Samella Botsford'),
       ('Karin Wolff'),
       ('Chasity Pfeffer'),
       ('Winfred Larkin'),
       ('Jackson Braun'),
       ('Kenyatta Kemmer'),
       ('Wilford Langworth'),
       ('Chi Cronin'),
       ('Otelia Grant'),
       ('Shaunna Nikolaus'),
       ('Mathew Mosciski'),
       ('Cary Hauck'),
       ('Wendi Glover'),
       ('Wiley Robel'),
       ('Edwin Abernathy'),
       ('Jacqui Veum'),
       ('Wyatt Schmidt'),
       ('Sean Pfeffer'),
       ('Jamie Steuber'),
       ('Valentina Medhurst'),
       ('Judy Breitenberg'),
       ('Quinton Brakus'),
       ('Elton Vandervort'),
       ('Kristan Wintheiser'),
       ('Ike Gibson'),
       ('Euna Purdy'),
       ('Solomon Rath'),
       ('Sharen Gerlach'),
       ('Oneida Corwin'),
       ('Jerica Daugherty'),
       ('Barry Corkery'),
       ('Charley Cruickshank'),
       ('Johnson Luettgen'),
       ('Tam Medhurst'),
       ('Judith Lubowitz'),
       ('Kai Murray'),
       ('Lincoln Leuschke'),
       ('Adalberto Paucek'),
       ('Burt Collier'),
       ('Lowell Pollich'),
       ('Trent Bergstrom'),
       ('Elijah Murphy'),
       ('Elaina Schultz'),
       ('Monte Beer'),
       ('Hattie Reinger'),
       ('Omar Zulauf'),
       ('Kirk Quigley'),
       ('Garfield Murphy'),
       ('Dana Batz'),
       ('Tanika Satterfield'),
       ('Dominique Bosco'),
       ('Charlie Beer'),
       ('Admin');

insert into user_credentials (encoded_password)
select '$2a$04$yzqTO7CMyoUhm5EYn9fu3.fq01S1.3amd7lJ7yvN6GlSMBx9fAtOe'
from user_profiles;

insert into users (user_profile_id, user_credential_id, username)
values (1, 1, 'darlena_runte'),
       (2, 2, 'tamiko_feest'),
       (3, 3, 'mel_rowe'),
       (4, 4, 'dorie_stamm'),
       (5, 5, 'derek_johns'),
       (6, 6, 'cyrus_bartoletti'),
       (7, 7, 'ezequiel_kub'),
       (8, 8, 'anibal_greenholt'),
       (9, 9, 'kaitlyn_gutmann'),
       (10, 10, 'celinda_erdman'),
       (11, 11, 'terina_nicolas'),
       (12, 12, 'alene_zieme'),
       (13, 13, 'cole_bins'),
       (14, 14, 'christoper_legros'),
       (15, 15, 'fausto_shanahan'),
       (16, 16, 'stephen_barton'),
       (17, 17, 'demetrius_borer'),
       (18, 18, 'sanford_prohaska'),
       (19, 19, 'noe_haley'),
       (20, 20, 'henriette_turcotte'),
       (21, 21, 'muriel_rath'),
       (22, 22, 'racquel_bayer'),
       (23, 23, 'tom_johns'),
       (24, 24, 'damion_marvin'),
       (25, 25, 'edmundo_powlowski'),
       (26, 26, 'damon_hagenes'),
       (27, 27, 'felton_greenfelder'),
       (28, 28, 'erline_wuckert'),
       (29, 29, 'georgann_gusikowski'),
       (30, 30, 'susanne_watsica'),
       (31, 31, 'leland_gusikowski'),
       (32, 32, 'sharice_hills'),
       (33, 33, 'shaina_jacobs'),
       (34, 34, 'danilo_lubowitz'),
       (35, 35, 'herman_kertzmann'),
       (36, 36, 'marybelle_lowe'),
       (37, 37, 'edwardo_rodriguez'),
       (38, 38, 'gabriella_berge'),
       (39, 39, 'sal_ziemann'),
       (40, 40, 'everette_macejkovic'),
       (41, 41, 'justine_mraz'),
       (42, 42, 'joshua_reichel'),
       (43, 43, 'serafina_mertz'),
       (44, 44, 'erwin_turner'),
       (45, 45, 'ena_gutkowski'),
       (46, 46, 'nicola_hyatt'),
       (47, 47, 'elton_cummerata'),
       (48, 48, 'carin_o''hara'),
       (49, 49, 'samella_botsford'),
       (50, 50, 'karin_wolff'),
       (51, 51, 'chasity_pfeffer'),
       (52, 52, 'winfred_larkin'),
       (53, 53, 'jackson_braun'),
       (54, 54, 'kenyatta_kemmer'),
       (55, 55, 'wilford_langworth'),
       (56, 56, 'chi_cronin'),
       (57, 57, 'otelia_grant'),
       (58, 58, 'shaunna_nikolaus'),
       (59, 59, 'mathew_mosciski'),
       (60, 60, 'cary_hauck'),
       (61, 61, 'wendi_glover'),
       (62, 62, 'wiley_robel'),
       (63, 63, 'edwin_abernathy'),
       (64, 64, 'jacqui_veum'),
       (65, 65, 'wyatt_schmidt'),
       (66, 66, 'sean_pfeffer'),
       (67, 67, 'jamie_steuber'),
       (68, 68, 'valentina_medhurst'),
       (69, 69, 'judy_breitenberg'),
       (70, 70, 'quinton_brakus'),
       (71, 71, 'elton_vandervort'),
       (72, 72, 'kristan_wintheiser'),
       (73, 73, 'ike_gibson'),
       (74, 74, 'euna_purdy'),
       (75, 75, 'solomon_rath'),
       (76, 76, 'sharen_gerlach'),
       (77, 77, 'oneida_corwin'),
       (78, 78, 'jerica_daugherty'),
       (79, 79, 'barry_corkery'),
       (80, 80, 'charley_cruickshank'),
       (81, 81, 'johnson_luettgen'),
       (82, 82, 'tam_medhurst'),
       (83, 83, 'judith_lubowitz'),
       (84, 84, 'kai_murray'),
       (85, 85, 'lincoln_leuschke'),
       (86, 86, 'adalberto_paucek'),
       (87, 87, 'burt_collier'),
       (88, 88, 'lowell_pollich'),
       (89, 89, 'trent_bergstrom'),
       (90, 90, 'elijah_murphy'),
       (91, 91, 'elaina_schultz'),
       (92, 92, 'monte_beer'),
       (93, 93, 'hattie_reinger'),
       (94, 94, 'omar_zulauf'),
       (95, 95, 'kirk_quigley'),
       (96, 96, 'garfield_murphy'),
       (97, 97, 'dana_batz'),
       (98, 98, 'tanika_satterfield'),
       (99, 99, 'dominique_bosco'),
       (100, 100, 'charlie_beer'),
       (101, 101, 'admin');

insert into roles (name)
values ('admin'),
       ('user');

insert into permissions (name)
values ('read'),
       ('write');

INSERT INTO role_permissions (permission_id, role_id)
SELECT p.id, r.id
FROM permissions p
         JOIN roles r ON r.name = 'admin';

INSERT INTO role_permissions (permission_id, role_id)
SELECT p.id, r.id
FROM permissions p
         JOIN roles r ON r.name = 'user'
WHERE p.name LIKE '%read';

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u
         JOIN roles r ON r.name = 'user'
WHERE u.username <> 'admin';

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u
         JOIN roles r ON r.name = 'admin'
WHERE u.username = 'admin';