alter table user_credentials
    alter column encoded_password drop not null;

alter table if exists user_auth_providers drop constraint if exists fk_user_auth_provider_user_id;
drop table if exists user_auth_providers cascade;
create table user_auth_providers
(
    id           integer generated by default as identity,
    user_id      integer,
    created_date timestamp(6) with time zone default NOW()   not null,
    email        varchar(255),
    provider     varchar(255)                default 'LOCAL' not null check ((provider in ('LOCAL', 'GOOGLE', 'FACEBOOK', 'GITHUB'))),
    provider_id  varchar(255),
    primary key (id),
    unique (provider, provider_id)
);
alter table if exists user_auth_providers add constraint fk_user_auth_provider_user_id foreign key (user_id) references users;